import { parseDeviceRef } from './core-domain-bridge.js';

function toBitKey(deviceToken, config) {
  const ref = parseDeviceRef(deviceToken, config);
  if (ref.kind !== 'BIT') {
    throw new Error(`ビットデバイスのみ対応: ${deviceToken}`);
  }
  return `${ref.base}:${ref.bitIndex}`;
}

function parseInstructions(source) {
  return String(source)
    .split('\n')
    .map((line) => line.trim())
    .filter(Boolean)
    .map((line) => {
      const [op, operand, arg] = line.split(/\s+/);
      return { op: (op ?? '').toUpperCase(), operand, arg, line };
    });
}

export function generateArduinoSketch({ source, config, scanCycleMs = 10 }) {
  const instructions = parseInstructions(source);
  const bitKeys = new Set();

  for (const ins of instructions) {
    if (ins.operand) {
      const bitKey = toBitKey(ins.operand, config);
      bitKeys.add(bitKey);
    }
  }

  const keys = Array.from(bitKeys);
  const keyLiterals = keys.map((k) => `  "${k}"`).join(',\n');

  const body = instructions
    .map((ins) => {
      if (!ins.operand) return `  // skip: ${ins.line}`;
      const key = toBitKey(ins.operand, config);
      if (ins.op === 'LD') return `  acc = getBit("${key}");`;
      if (ins.op === 'LDN') return `  acc = !getBit("${key}");`;
      if (ins.op === 'OUT') return `  setBit("${key}", acc);`;
      if (ins.op === 'SET') return `  if (acc) setBit("${key}", true);`;
      if (ins.op === 'RST') return `  if (acc) setBit("${key}", false);`;
      if (ins.op === 'TON') return `  // TON簡易: acc時に完了ビットON\n  setBit("${key}", acc);`;
      if (ins.op === 'CTU') return `  // CTU簡易: acc時に完了ビットON\n  if (acc) setBit("${key}", true);`;
      return `  // 未対応命令: ${ins.line}`;
    })
    .join('\n');

  return `// Auto-generated by LadduinoIDE\n#include <Arduino.h>\n#include <string.h>\n\nstatic const char* BIT_KEYS[] = {\n${keyLiterals || '  "__dummy__:0"'}\n};\nstatic bool BIT_VALS[${Math.max(keys.length, 1)}] = {false};\nstatic const int BIT_COUNT = ${Math.max(keys.length, 1)};\n\nint bitIndex(const char* key) {\n  for (int i = 0; i < BIT_COUNT; i++) {\n    if (strcmp(BIT_KEYS[i], key) == 0) return i;\n  }\n  return -1;\n}\n\nbool getBit(const char* key) {\n  int idx = bitIndex(key);\n  return idx >= 0 ? BIT_VALS[idx] : false;\n}\n\nvoid setBit(const char* key, bool value) {\n  int idx = bitIndex(key);\n  if (idx >= 0) BIT_VALS[idx] = value;\n}\n\nvoid ladderScan() {\n  bool acc = false;\n${body}\n}\n\nvoid setup() {\n  Serial.begin(921600);\n}\n\nvoid loop() {\n  ladderScan();\n  delay(${Number(scanCycleMs) || 10});\n}\n`;
}
